# ----------------------------------Vega Auth API---------------------------------#
### GET API Token
POST http://localhost:8000/auth/token
cache-control: no-cache
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

> {% client.global.set("token", JSON.parse(JSON.stringify(response.body))["token"]);%}

### GET Semaphore Projects
GET http://localhost:8000/api/semaphore/projects
Authorization: Bearer {{token}}

### POST Semaphore Run Task Template
POST http://localhost:8000/api/semaphore/run-task-template
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "template_id": 2
}
